### ISSUE TITLE
TypeError: unsupported operand type(s) for 'in': 'str' and 'EnumMeta'

### ISSUE THREAD

**Issue by BATMAN-JD** [arcalot/arcaflow-plugin-sdk-python#77] opened 2022-10-18 14:55 UTC
## Describe the bug

When building a schema from an enum, the serialize function results in an error as shown in [this fio carpenter build.](https://github.com/arcalot/arcaflow-plugin-fio/actions/runs/3273866289/jobs/5387216765)
Looks like it built fine through history with 0.4.2 being called from [here](https://github.com/arcalot/arcaflow-plugin-fio/blob/dc3882b115ee084fbfe17540ad4c3066c87c7af6/fio_schema.py#L744)

### Requirements

- carpenter [binary](https://github.com/arcalot/arcaflow-plugin-image-builder)
- fio project

```shell
docker run \
    --rm \
    -e=IMAGE_TAG="0.0.1"\
    --volume /var/run/docker.sock:/var/run/docker.sock:z \
    --volume $PWD/../arcaflow-plugin-fio:/github/workspace:z \
    carpenter-img build --build
```

**Comment by dustinblack** [comment] 2023-06-12 15:33
Duplicate of #83

**Closed as completed by dustinblack** 2023-06-12 15:33 UTC
Labels: bug
